### ISSUE TITLE
[ERROR] apiRequest failed. URLError: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by sebma** [realriot/ff4d#15]
Hi,

I'm running `ff4d` for the very first time and maybe I forgot to do something along the way.

Here is what I get : 

```
$ mkdir ~/testDropBox
$ ./ff4d.py -d ~/testDropBox/
********************************************************
* FUSE Filesystem 4 Dropbox                            *
*                                                      *
* Copyright 2014                                       *
* Sascha Schmidt <sascha@schmidt.ps>                   *
*                                                      *
* https://github.com/realriot/ff4d/blob/master/LICENSE *
********************************************************

[INFO] No accesstoken available. Fetching a new one.

Please choose which permission this application will request:
Enter 'd' - This application will have access to your whole
            Dropbox.
Enter 's' - This application will just have access to its
            own application folder.

Please enter permission key: d
[DEBUG] Initialzed apiAuth
[DEBUG] Trying to fetch apiAuth code: dropbox fg7v60fm9f5ud7n
[ERROR] apiRequest failed. URLError: [Errno -2] Name or service not known
[DEBUG] Failed to fetch apiAuth code (Traceback (most recent call last):
  File "./ff4d.py", line 598, in getCode
    result = self.apiRequest.get("https://tools.schmidt.ps/authApp", args)
  File "./ff4d.py", line 536, in get
    raise Exception, 'apiRequest failed. URLError: ' + str(e.reason)
Exception: apiRequest failed. URLError: [Errno -2] Name or service not known
)
Failed to start authorization process
[DEBUG] Got accesstoken from user input: False
[ERROR] No valid accesstoken available. Exiting.
$ echo $?
255
```

Can you help ?

**Comment by theluckyluke** [comment]
It's trying to access a webservice that isn't available anymore (https://tools.schmidt.ps/authApp). See #14 for more info.

You'll have to create an access token using getDropboxAccessToken.py, this doesn't require the webservice.

**Comment by realriot** [comment]
Rewritten code. Pls test again.
