### ISSUE TITLE
apiRequest failed. HTTPError: 404

### ISSUE THREAD

**Issue by andreafabrizi** [realriot/ff4d#7]
After successfully setting up the app providing app key and secret, at the first run I get the following error:

```
./ff4d.py -d /tmp/dropbox
********************************************************
* FUSE Filesystem 4 Dropbox                            *
*                                                      *
* Copyright 2014                                       *
* Sascha Schmidt <sascha@schmidt.ps>                   *
*                                                      *
* https://github.com/realriot/ff4d/blob/master/LICENSE *
********************************************************

[INFO] No accesstoken available. Fetching a new one.

Please choose which permission this application will request:
Enter 'd' - This application will have access to your whole
            Dropbox.
Enter 's' - This application will just have access to its
            own application folder.

Please enter permission key: d
[DEBUG] Initialzed apiAuth
[DEBUG] Trying to fetch apiAuth code: dropbox fg7v60fm9f5ud7n
[ERROR] apiRequest failed. HTTPError: 404
[DEBUG] Failed to fetch apiAuth code (Traceback (most recent call last):
  File "./ff4d.py", line 598, in getCode
    result = self.apiRequest.get("https://tools.schmidt.ps/authApp", args)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 404
)
Failed to start authorization process
[DEBUG] Got accesstoken from user input: False
[ERROR] No valid accesstoken available. Exiting.
```

Thanks

**Comment by mattdell** [comment]
You don't want to use the app key and secret key here. You want to use a generated token under the OAuth section, a few fields below your app and secret keys.

I had the same problem!

**Comment by andreafabrizi** [comment]
@mattdell, did you managed to make it works?

**Comment by mattdell** [comment]
Yep. It worked for me once I generated an OAuth token.
````
./ff4d.py -d -df -at <your oauth token here> /tmp/dropbox
````
You can also use -ap to keep the token permanently.

**Comment by realriot** [comment]
Rewritten code. Pls test again.
